"""Movement and sizing constants for early gameplay entities."""

PLAYER_SPEED = 4.0
TANK_SIZE = 24
ALIGNMENT_THRESHOLD = 6.0
PLAYER_BULLET_SPEED = 10.0
PLAYER_BULLET_RADIUS = 4
ENEMY_SPEED = 2.0
FAST_ENEMY_SPEED = 2.6
ARMOR_ENEMY_SPEED = 1.8
ARMOR_ENEMY_RETREAT_THRESHOLD = 1
ARMOR_ENEMY_RETREAT_DECISION_INTERVAL = 12
ENEMY_DECISION_INTERVAL = 22
FAST_ENEMY_DECISION_INTERVAL = 14
ARMOR_ENEMY_DECISION_INTERVAL = 18
BOSS_ENEMY_SPEED = 2.2
BOSS_ENEMY_DECISION_INTERVAL = 10
ENEMY_BULLET_SPEED = 6.5
ENEMY_BULLET_RADIUS = 4
MAX_ACTIVE_ENEMIES = 3
BASIC_ENEMY_STUCK_TICKS = 12
ARMOR_ENEMY_HIT_POINTS = 2
BOSS_ENEMY_HIT_POINTS = 10
