"""Movement and sizing constants for early gameplay entities."""

PLAYER_SPEED = 4.0
TANK_SIZE = 24
ALIGNMENT_THRESHOLD = 6.0
PLAYER_BULLET_SPEED = 10.0
PLAYER_BULLET_RADIUS = 4
ENEMY_SPEED = 2.5
ENEMY_DECISION_INTERVAL = 18
ENEMY_BULLET_SPEED = 8.0
ENEMY_BULLET_RADIUS = 4
MAX_ACTIVE_ENEMIES = 3
BASIC_ENEMY_STUCK_TICKS = 12
