"""Static configuration for the initial Pygame bootstrap."""

GRID_WIDTH = 26
GRID_HEIGHT = 26
TILE_SIZE = 32

MAP_WIDTH = GRID_WIDTH * TILE_SIZE
MAP_HEIGHT = GRID_HEIGHT * TILE_SIZE

HUD_WIDTH = 280
SCREEN_WIDTH = MAP_WIDTH + HUD_WIDTH
SCREEN_HEIGHT = MAP_HEIGHT

FPS = 60
WINDOW_TITLE = "Battle City AI"

BACKGROUND_COLOR = (18, 18, 24)
HUD_BACKGROUND_COLOR = (28, 31, 40)
TEXT_COLOR = (240, 240, 240)
